// mutation types
export const USER_LOGIN_SUCCESS = 'USER_LOGIN_SUCCESS'
export const FETCH_ALBUM_LIST_SUCCESS = 'FETCH_ALBUM_LIST_SUCCESS'
export const ALBUM_LOAD_ENDED = 'ALBUM_LOAD_ENDED'
export const CREATE_ALBUM_LIST_SUCCESS = 'CREATE_ALBUM_LIST_SUCCESS'
export const DELETE_ALBUMS_SUCCESS = 'DELETE_ALBUMS_SUCCESS'
